application: zeepooling-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheet
  static_dir: stylesheet

- url: /image/(.*\.(gif|png|jpg))
  static_files: image/\1
  upload: image/(.*)

- url: /favicon\.ico
  static_files: image/favicon.ico
  upload: image/(.*)

- url: /.*
  script: home.app
  

libraries:
- name: django
  version: "1.2"